title: SUN Tiantong's Homepage
page-top-title: SUN Tiantong
top-section-bg-text: Mathematics
home-subtitle: SUN Tiantong &ensp;|&ensp;孙天同
copyright-text: '&copy;SUN Tiantong 2023-2024. All Rights Reserved.'
